- hosts: terraform-ansible
  become: yes
  tasks:
  - name: Download pip installer
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
  - name: instalando o python3
    apt:
      pkg:
      - python3
      - python3-pip
      - python3-venv
      update_cache: yes
  - name: Create app folder
    file:
      name: /opt/pythonapp
      state: directory
      recurse: yes
  - name: Install virtualenv module
    pip:
      name: virtualenv
      state: latest
  - name: 'instalando depenencias com pip (Django e Django rest)'
    pip:
      virtualenv: /home/ubuntu/venv/venv
      name:
        - django
        - djangorestframework